In [29]:
import pandas as pd
import numpy as np

# The Purpose

Look at specialty referrals in Seattle.

# The Data

In [3]:
df = pd.read_csv("../Data/Choice_Referrals/outside authorizations - FY15.csv")

In [36]:
card['Station '].rename('Station')

8         402
9         402
10        402
11        402
12        402
80        405
81        405
82        405
83        405
146       436
147       436
148       436
149       436
150       436
223       437
224       437
225       437
226       437
227       437
294       438
295       438
296       438
297       438
298       438
368       442
369       442
370       442
371       442
372       442
439       459
        ...
9094    528A8
9151    589A4
9152    589A4
9212    589A5
9213    589A5
9214    589A5
9215    589A5
9216    589A5
9277    589A7
9278    589A7
9279    589A7
9280    589A7
9347    636A6
9348    636A6
9349    636A6
9416    636A8
9417    636A8
9418    636A8
9419    636A8
9420    636A8
9487    657A4
9488    657A4
9489    657A4
9490    657A4
9491    657A4
9554    657A5
9555    657A5
9556    657A5
9557    657A5
9558    657A5
Name: Station, dtype: object

# Analysis

In [52]:
card = df[df["Service Descriptor"].str.contains("Card").fillna(False)]
card_sum = pd.pivot_table(card,index=["Station "],values=['NumAuths','NumVets'],aggfunc=np.sum).reset_index()
card_sum

    Station         NumAuths         NumVets
0        402     41001261112       496851112
1        405          829427          821366
2        436  90123274411237  87116189611231
3        437   4210867216537   4110348716509
4        438       757103103        75495103
5        442       545117830       443103730
6        459    101916201558    101913411524
7        460          613481          613381
8        463     88826851251     87716591245
9        501      1164370113      1163354113
10       502       146340721       125254721
11       503       842136217       836127217
12       504     30273551021      2224262921
13       506         9439785         8428785
14       508      8163237644      8160217642
15       509    171650699116    151582678113
16       512         1339859         1238559
17       515         5998968         5958168
18       516    201236091654    181155821653
19       517          471124          471074
20       518            3464            3464
21       519     32446523399     32415723388
22       520     52344535213     44636413113
23       521     21402911511     19392661511
24       523          122411          111811
25       526              67              67
26       528       744470370       743404369
27     528A5       323410522       322327522
28     528A6           11693           11663
29     528A7    719220129135    718196128129
..       ...             ...             ...
110      657           21511           21281
111    657A4       410235314        49194313
112    657A5      1510930447      1310626047
113      658        47269101        47065101
114      659     10154277843     10148201840
115      660       228216923       227193922
116      662       237248235       235202235
117      663       793728235       793525635
118      664       311212625       310211724
119      666     15524433828     13482963728
120      667          163521          163231
121      668       854187410       852148310
122      671       112327322       111425722
123      672         6133784         6129184
124      673          412012          411612
125      674        12745636        12734986
126      675     12102073140      1291863139
127      676         1841324         1751224
128      678     21241503012     21111282711
129      679      1011286234       109179230
130      687    637392134216    635340131206
131      688           12714           12713
132      689          251611          248501
133      691         5312127         4310226
134      692       522309678       521226577
135      693        74513464        69512064
136      695       219181423       179162422
137      740       484173110       482596110
138      756     12617781814     11596381814
139      757        69938514        69133714

[140 rows x 3 columns]

In [45]:
card["NumVets"].mean()

inf

In [44]:
card.median()

Series([], dtype: float64)

In [49]:
card["NumVets"]

8          4
9         96
10        85
11        11
12        12
80         8
81        21
82        36
83         6
146       87
147      116
148     1896
149       11
150      231
223       41
224      103
225      487
226       16
227      509
294        7
295       54
296       95
297       10
298        3
368        4
369       43
370      103
371        7
372       30
439       10
        ...
9094       2
9151     112
9152      77
9212      18
9213      51
9214     800
9215       3
9216      82
9277       2
9278      61
9279      69
9280       1
9347       6
9348      73
9349      40
9416       4
9417     132
9418     133
9419       3
9420       5
9487       4
9488       9
9489     194
9490       3
9491      13
9554      13
9555     106
9556     260
9557       4
9558       7
Name: NumVets, dtype: object